####  application-dev.yml
server:
  port: 8001
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper.xml文件位置
  mapper-locations: classpath:com/wzd/eduservice/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
spring:
  application:
    name: service-edu
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_learning?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: root
  hikari:
    connection-test-query: SELECT 1
    connection-timeout: 60000
    idle-timeout: 500000
    max-lifetime: 540000
    maximum-pool-size: 12
    minimum-idle: 10
    pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000
#开启熔断机制
feign:
  hystrix:
    enabled: true
# 设置hystrix超时时间，默认1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
#日志级别
#logging:
#  level:
#    root: info
